# Generated by Django 4.2.7 on 2026-03-06 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +7(999)-999-99-99', regex='^\\+7\\(\\d{3}\\)-\\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
